sudo: false
language: scala
dist: trusty
matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    jdk: openjdk7
  - env: SBT_VERSION="1.0.4"
    jdk: oraclejdk8
cache:
  directories:
  - $HOME/gae-sdk
before_install:
- pushd $HOME/gae-sdk
- SDK=appengine-java-sdk-1.9.62
- SDK_ZIP=$SDK.zip
- wget -N https://storage.googleapis.com/appengine-sdks/featured/$SDK_ZIP
- unzip $SDK_ZIP
- export APPENGINE_SDK_HOME=$HOME/gae-sdk/$SDK
- popd
before_cache:
- rm -rf $HOME/gae-sdk/$SDK/
script:
- sbt "^^ ${SBT_VERSION}" compile test scripted
